license: agpl-3.0-or-later
sources:
  rubygem: true
allowed:
  - apache-2.0
  - mit
ignored:
  rubygem:
    - bundler
reviewed:
  rubygem:
    - bcrypt
    - concurrent-ruby
    - method_source
    - nokogiri
    - pg
    - puma
    - rack
